<?php

if (isset($_SESSION['user'])) {
    $pseudo = $_SESSION['user']['pseudo'];
    $avatar = $_SESSION['user']['avatar'];
    $email = $_SESSION['user']['email'];
}

//if user identified has admin role, display all users in table
if (array_filter($_SESSION) && $_SESSION['user']['role'] === 'admin') {

?>

<main class="admin-main">
    <section class="admin-lateral-bar">
    <div>
        <p class="admin-avatar"><img src="<?= $avatar ?>" alt=""style="width:175px"></p>
        <p>MON PROFILE</p>
        <p><?= $pseudo ?></p>
        <p><?= $email ?></p>
        <p>Éditer le profile</p>
    </div>
    <div>
        <p><a href="index.php?route=logout">Déconnexion</a></p>
    </div>

    </section>

    <section class="admin-main-content">
    <h1>Administrer les dévots de Johnny</h1>

                   <script>
        function PlaySound(soundobj) {
            var thissound = document.getElementById(soundobj);
            thissound.play();
        }
    </script>
    <a class="admin-label-search" href="index.php?route=inscription&create=true">Ajouté un nouveau fan</a>
    <form class="admin-search-bar" action="./index.php?route=admin" method="post"><label for="search"></label> <input type="text" id="search" name="search"> <button type="submit">Recherché un fan</button></form>
    <a class="admin-see-all" href="./index.php?route=admin">Voir tous les fans</a>

    <?php
    if (array_filter($_POST)) {
        $search = $_POST['search'];
    ?>
        <p>Résultats de la recherche pour "<?= $search ?>":</p>
    <?php
    }
    ?>

    <?php

    ?>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Avatar</th>
                <th>Pseudo</th>
                <th>Email</th>
                <th>Role</th>
                <th colspan="3">Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php
            $query = $db->prepare('SELECT * FROM users');
            $parameters = [];
            $query->execute($parameters);
            $users = $query->fetchAll(PDO::FETCH_ASSOC);
            foreach ($users as $user) {
                if (array_filter($_POST)) {
                    if (!preg_match("/$search/i", $user['pseudo']) && !preg_match("/$search/i", $user['email'])) {
                        continue;
                    };
                };
            ?>
                <tr>
                    <td><?= $user['user_id'] ?></td>
                    <td><img src="<?= $user['avatar'] ?>" alt="" style="width:60px"></td>
                    <td><?= $user['pseudo'] ?></td>
                    <td><?= $user['email'] ?></td>
                    <td><?= $user['role'] ?></td>
                    <td><a onmouseover="PlaySound('mySound')" href="./logic/admin.php?delete=<?= $user['email'] ?>">Zigouiller</a>
                    <td><a href="./logic/admin.php?modify=<?= $user['email'] ?>">Modifier</a>

                        <?php
                        if ($user['role'] === 'admin') {
                        ?>
                            <a href="./logic/admin.php?toggleAdmin=true&email=<?= $user['email'] ?>">Enlever l'héritage</a>
                        <?php
                        } else {
                        ?>
                            <a href="./logic/admin.php?toggleAdmin=false&email=<?= $user['email'] ?>">Donner l'héritage</a>
                        <?php
                        }
                        ?>
                    </td>
                </tr>
            <?php
            } ?>
        </tbody>
    </table>
<?php
    //If no admin indentified give error message
} else {
?>
    <p>Vous n'avez pas le pouvoir nécessaire pour manager les dévots de Johnny...</p>
    <img src="https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExZWUyOTJpNGRta2Z0ZDBqYjl2bnQ2dXRxdDl0dDhudHFzNDN5dnBwaCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/RX3vhj311HKLe/giphy.gif" alt="">
    <br>
<?php
}
?>
<a href="./index.php?route=home">Revenir à l'accueil</a>


    </section>
<audio id='mySound' src='./assets/Sasageyo-short.mp3'></audio>

