<?php
//if user identified has admin role, display all users in table
if (array_filter($_SESSION) && $_SESSION['user']['role'] === 'admin') {

?>
    <h1>Administrer les dévots de Johnny</h1>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Avatar</th>
                <th>Pseudo</th>
                <th>Email</th>
                <th>Role</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php
            $query = $db->prepare('SELECT * FROM users');
            $parameters = [];
            $query->execute($parameters);
            $users = $query->fetchAll(PDO::FETCH_ASSOC);
            foreach ($users as $user) {
            ?>
                <tr>
                    <td><?= $user['user_id'] ?></td>
                    <td><img src="<?= $user['avatar'] ?>" alt="" style="width:60px"></td>
                    <td><?= $user['pseudo'] ?></td>
                    <td><?= $user['email'] ?></td>
                    <td><?= $user['role'] ?></td>
                    <td><a href="./logic/admin.php?delete=<?= $user['email'] ?>">Delete</a>
                    <td><a href="./logic/admin.php?modify=<?= $user['email'] ?>">Modify</a>

                        <?php
                        if ($user['role'] === 'admin') {
                        ?>
                            <a href="./logic/admin.php?toggleAdmin=true&email=<?= $user['email'] ?>">Delete admin rights</a>
                        <?php
                        } else {
                        ?>
                            <a href="./logic/admin.php?toggleAdmin=false&email=<?= $user['email'] ?>">Give admin rights</a>
                        <?php
                        }
                        ?>
                    </td>
                </tr>
            <?php
            } ?>
        </tbody>
    </table>
<?php
    //If no admin indentified give error message
} else {
?>
    <p>Vous n'avez pas le pouvoir nécessaire pour manager les dévots de Johnny...</p>
    <img src="https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExZWUyOTJpNGRta2Z0ZDBqYjl2bnQ2dXRxdDl0dDhudHFzNDN5dnBwaCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/RX3vhj311HKLe/giphy.gif" alt="">
    <br>
<?php
}
?>
<a href="./index.php?route=home">Revenir à l'accueil</a>