<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Marcellus+SC&family=Roboto+Condensed:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="style/style.css">
    <title>Johnny Lovers</title>
</head>

<body>

    <?php
    require "header.phtml";
    if ($route === null || preg_match("/home/", $route)) {
        require "home.phtml";
    } else if (preg_match("/inscription/", $route)) {
        require "register.phtml";
    } else if (preg_match("/connexion/", $route)) {
        require "login.phtml";
    } else if (preg_match("/logout/", $route)) {
        require "logout.phtml";
    } else if (preg_match("/admin/", $route)) {
        require "admin-space.phtml";
    } else if (preg_match("/song/", $route)) {
        require "song.phtml";
    }

    ?>
    <script src="https://kit.fontawesome.com/c75c1791b5.js" crossorigin="anonymous"></script>
</body>

</html>