<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Johnny Lovers</title>
</head>

<body>

    <?php

    if ($route === null || preg_match("/home/", $route)) {
        require "home.phtml";
    } else if (preg_match("/inscription/", $route)) {
        require "register.phtml";
    } else if (preg_match("/connexion/", $route)) {
        require "login.phtml";
    } else if (preg_match("/logout/", $route)) {
        require "logout.phtml";
    } else if (preg_match("/admin/", $route)) {
        require "admin-space.phtml";
    } else if (preg_match("/song/", $route)) {
        require "song.phtml";
    } else if (preg_match("/modify/", $route)) {
        require "modify.phtml";
    }
    ?>

</body>

</html>