<form class="register-login-form" action="./logic/login.php" method="post">
    <h1>Connection</h1>
    <label for="email">Email:</label>
    <input type="email" name="email" id="email">
    <label for="password">Password:</label>
    <input type="password" name="password" id="password">
    <button type="submit">Revenir parmi les vivants

    </button>
    <p class="form-link-bottom">Pas encore de compte? <a href="./index.php?route=inscription">S'inscrire</a></p>
    <p class="form-link-bottom">
        <a href="./index.php?route=home">Revenir à l'accueil</a>
    </p>
</form>

<div class="audio-wrapper">
    <audio src="/assets/Sasageyo.mp3" controls>
    </audio>
</div>


<script>
    let formElements = document.querySelectorAll('form > *');
    formElements.forEach(element => {
        element.addEventListener('focus', () => {
            document.querySelector("audio").play();
        });
    });
</script>