<h1>Rejoignez-nous</h1>
<?php
if (isset($_GET['error'])) {
?>
    <p>L'email "<?= $_GET['error'] ?>" est déjà utilisé</p>
    <p>Veuillez en saisir un autre ou vous connecter via la page Login.</p>
<?php
}
?>
<form action="./logic/register.php" method="post">
    <label for="pseudo">Pseudo:</label>
    <input type="text" name="pseudo" id="pseudo" required>
    <label for="email">Email:</label>
    <input type="email" name="email" id="email" required>
    <label for="avatar">Avatar:</label>
    <input type="text" name="avatar" id="avatar">
    <label for="password">Password:</label>
    <input type="password" name="password" id="password" required>

    <button type="submit">Attendons Johnny ensemble !
    </button>
</form>

<a href="./index.php?route=home">Revenir à l'accueil</a>