<h1>La musique de Johnny</h1>
<script>
    function PlaySound(soundobj) {
        var thissound = document.getElementById(soundobj);
        thissound.play();
    }
</script>
<?php
//if user authentified, personnalize greetings
if (isset($_SESSION['user'])) {
    $pseudo = $_SESSION['user']['pseudo'];
    $email = $_SESSION['user']['email'];
    $favoriteSong = $_SESSION['user']['favoriteSong'];
    // var_dump($_SESSION);
?>
    <p>Choisissez votre chanson préferée <?= $pseudo ?> </p>
    <?php
    //display grid of videos and choose url for favorite song
    $query = $db->prepare('SELECT * FROM songs');
    $parameters = [];
    $query->execute($parameters);
    $songs = $query->fetchAll(PDO::FETCH_ASSOC);
    foreach ($songs as $song) {
    ?>

        <div class="song-card">

            <h2><?= $song['title'] ?></h2>
            <iframe width="560" height="315" src="<?= $song['url'] ?>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            <?php
            if ($favoriteSong === $song['song_id']) {
            ?>
                <a onmouseover="PlaySound('mySound')" href="./logic/song.php?toggleSong=true&song_id=<?= $song['song_id'] ?>">Enlever de ma chanson favorite</a>
            <?php
            } else {
            ?>
                <a onmouseover="PlaySound('mySound')" href="./logic/song.php?toggleSong=false&song_id=<?= $song['song_id'] ?>">Sélexionner comme chason favorite</a>
        </div>
    <?php
            }
    ?>


<?php
    }
    //if user has admin role, add a link to admin page
    if ($_SESSION['user']['role'] === "admin") {
?>
    <a href="index.php?route=admin">Manage users</a>
<?php
    };
?>
<a href="index.php?route=song">Choisir ma chanson préferée</a>
<a href="index.php?route=logout">Logout</a>
<audio id='mySound' src='./assets/Rondoudou.mp3'></audio>
<?php
} else {
?>
    <p>Welcome</p>
    <a href="index.php?route=inscription">Register</a>
    <a href="index.php?route=connexion">Login</a>
<?php
}
?>