<script>
    function PlaySound(soundobj) {
        var thissound = document.getElementById(soundobj);
        thissound.play();
    }
</script>

<?php
//if user authentified, personnalize greetings
if (isset($_SESSION['user'])) {
    $pseudo = $_SESSION['user']['pseudo'];
    $email = $_SESSION['user']['email'];
    $favoriteSong = $_SESSION['user']['favoriteSong'];
    $avatar = $_SESSION['user']['avatar'];
}
?>
<main class="song-main">
    <section class="song-lateral-bar">
        <div>
            <p class="song-avatar"><img src="<?= $avatar ?>" alt="" style="width:175px"></p>
            <p>MON PROFILE</p>
            <p><?= $pseudo ?></p>
            <p><?= $email ?></p>
            <p>Éditer le profile</p>
        </div>
        <div>
            <p><a href="index.php?route=logout">Déconnexion</a></p>
        </div>

    </section>

    <section class="song-main-content">

        <h1>Ma chanson favorite</h1>
        <?php
        //if user authentified, personnalize greetings
        if (isset($_SESSION['user'])) {
            $pseudo = $_SESSION['user']['pseudo'];
            $email = $_SESSION['user']['email'];
            $favoriteSong = $_SESSION['user']['favoriteSong'];
        ?>
            <div class="wrapper">
                <?php
                //display grid of videos and choose url for favorite song
                $query = $db->prepare('SELECT * FROM songs');
                $parameters = [];
                $query->execute($parameters);
                $songs = $query->fetchAll(PDO::FETCH_ASSOC);
                foreach ($songs as $song) {
                ?>

                    <div class="song-card">

                        <h2><?= $song['title'] ?></h2>
                        <iframe width="450" height="253" src="<?= $song['url'] ?>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe><br><br>
                        <?php
                        if ($favoriteSong === $song['song_id']) {
                        ?>

                            <a class="song-fav-button" onmouseover="PlaySound('mySound')" href="./logic/song.php?toggleSong=true&song_id=<?= $song['song_id'] ?>">Enlever de ma chanson favorite</a>
                    </div>
                <?php
                        } else {
                ?>
                    <a class="song-fav-button" onmouseover="PlaySound('mySound')" href="./logic/song.php?toggleSong=false&song_id=<?= $song['song_id'] ?>">Sélexionner comme chason favorite</a>

            </div>

        <?php
                        }
        ?>
    <?php

                }
                //if user has admin role, add a link to admin page
                if ($_SESSION['user']['role'] === "admin") {
    ?>
        </div>

    <?php
                };

    ?>
<?php
        } else {
?>

    <p>Welcome</p>
    <a href="index.php?route=inscription">Register</a>
    <a href="index.php?route=connexion">Login</a>
    <audio id='mySound' src='./assets/Rondoudou.mp3'></audio>
<?php
        }
?>
    </section>

</main>